// This file is auto-generated by kysely-codegen
// To regenerate: npm run generate-types (requires DATABASE_URL)

declare module 'kysely-codegen' {
  export type Privacy = 'public' | 'private'

  export type PostProcessingStatus =
    | 'pending'
    | 'processing'
    | 'completed'
    | 'failed'
    | 'background_removal_failed'
    | 'convert_to_svg_failed'

  export interface PixelTable {
    id: string
    userId: string
    prompt: string
    createdAt: Date
    updatedAt: Date | null
    showExplore: boolean
    privacy: Privacy
  }

  export interface PixelVersionTable {
    id: string
    pixelId: string
    fileKey: string
    version: number
    isCurrent: boolean
    createdAt: Date
  }

  export interface PostProcessingTable {
    id: string
    pixelId: string
    pngOriginalFileKey: string
    pngNobgFileKey: string | null
    status: PostProcessingStatus
    errorMessage: string | null
    completedAt: Date | null
    createdAt: Date
    updatedAt: Date | null
  }

  export interface DB {
    pixel: PixelTable
    pixelVersion: PixelVersionTable
    postProcessing: PostProcessingTable
  }
}
