/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type PostProcessingStatus = "background_removal" | "background_removal_failed" | "completed" | "convert_to_svg" | "convert_to_svg_failed" | "initiated";

export type Privacy = "private" | "private" | "public" | "public";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Timestamp;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Jwks {
  createdAt: Timestamp;
  id: string;
  privateKey: string;
  publicKey: string;
}

export interface Pixel {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  privacy: Generated<Privacy>;
  prompt: string;
  showExplore: Generated<boolean>;
  updatedAt: Timestamp | null;
  userId: string;
}

export interface PixelVersion {
  createdAt: Generated<Timestamp | null>;
  fileKey: string;
  gridSize: Generated<number | null>;
  id: Generated<string>;
  isCurrent: Generated<boolean | null>;
  pixelId: string;
  version: Generated<number>;
}

export interface PostProcessing {
  completedAt: Timestamp | null;
  errorMessage: string | null;
  id: Generated<string>;
  pixelId: string;
  pngNoBgFileKey: string | null;
  pngOriginalFileKey: string | null;
  startedAt: Generated<Timestamp | null>;
  status: Generated<PostProcessingStatus>;
}

export interface User {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Timestamp;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  role: string | null;
  updatedAt: Timestamp;
}

export interface Verification {
  createdAt: Timestamp | null;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Timestamp | null;
  value: string;
}

export interface DB {
  account: Account;
  jwks: Jwks;
  pixel: Pixel;
  pixelVersion: PixelVersion;
  postProcessing: PostProcessing;
  user: User;
  verification: Verification;
}
