// This file is auto-generated by kysely-codegen
// To regenerate: bun generate-types (requires DATABASE_URL)

declare module 'kysely-codegen' {
  import type { ColumnType, Generated } from 'kysely'

  export type Privacy = 'public' | 'private'

  export type PostProcessingStatus =
    | 'pending'
    | 'processing'
    | 'background_removal'
    | 'background_removal_failed'
    | 'convert_to_svg'
    | 'convert_to_svg_failed'
    | 'completed'
    | 'failed'

  export interface PixelTable {
    id: string
    userId: string
    prompt: string
    createdAt: Generated<Date>
    updatedAt: Date | null
    showExplore: Generated<boolean>
    privacy: Generated<Privacy>
  }

  export interface PixelVersionTable {
    id: string
    pixelId: string
    fileKey: string
    version: number
    isCurrent: boolean
    createdAt: Generated<Date>
  }

  export interface PostProcessingTable {
    id: string
    pixelId: string
    pngOriginalFileKey: string
    pngNobgFileKey: string | null
    status: Generated<PostProcessingStatus>
    errorMessage: string | null
    completedAt: Date | null
    createdAt: Generated<Date>
    updatedAt: Date | null
  }

  export interface DB {
    pixel: PixelTable
    pixelVersion: PixelVersionTable
    postProcessing: PostProcessingTable
  }
}
